package sbz;

import sbz.biochemical.analysis.model.analysis.SymptomsAndDiseases;
import sbz.biochemical.analysis.model.analysis.Diagnosis;
import constants.SymptomsList;
import constants.Diseases;

global Diagnosis diagnosis;

rule "Colon cancer symptoms"
    when
        $s: SymptomsAndDiseases($sl: symptoms, $dl: diseasesList contains Diseases.COLON_CANCER)
        $count: Number(intValue >= 2) from accumulate(
            String(
                toString() memberOf SymptomsList.colonCancerSymptoms
            ) from $sl,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        String disease = "Colon cancer";
        if($count.intValue() > 3) {
            diagnosis.setMostLikelyDisease(disease);
        }

        if ($count.intValue() > 2) {
            diagnosis.getHighChanceDiseases().add(disease);
        } else {
            diagnosis.getPossibleDiseases().add(disease);
        }
end

rule "Lung cancer symptoms"
    when
        $s: SymptomsAndDiseases($sl: symptoms, $dl: diseasesList contains Diseases.LUNG_CANCER)
        $count: Number(intValue >= 2) from accumulate(
            String(
                toString() memberOf SymptomsList.lungCancerSymptoms
            ) from $sl,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        String disease = "Lung cancer";
        if($count.intValue() > 3) {
            diagnosis.setMostLikelyDisease(disease);
        }

        if ($count.intValue() > 2) {
            diagnosis.getHighChanceDiseases().add(disease);
        } else {
            diagnosis.getPossibleDiseases().add(disease);
        }
end

rule "Chikungunya virus symptoms"
    when
        $s: SymptomsAndDiseases($sl: symptoms, $dl: diseasesList contains Diseases.CHIKUNGUNYA_VIRUS)
        $count: Number(intValue >= 2) from accumulate(
            String(
                toString() memberOf SymptomsList.chikungunyaVirusSymptoms
            ) from $sl,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        String disease = "Chikungunya virus";
        if($count.intValue() > 3) {
            diagnosis.setMostLikelyDisease(disease);
        }

        if ($count.intValue() > 2) {
            diagnosis.getHighChanceDiseases().add(disease);
        } else {
            diagnosis.getPossibleDiseases().add(disease);
        }
end

rule "Trench fever symptoms"
    when
        $s: SymptomsAndDiseases($sl: symptoms, $dl: diseasesList contains Diseases.TRENCH_FEVER)
        $count: Number(intValue >= 2) from accumulate(
            String(
                toString() memberOf SymptomsList.trenchFeverSymptoms
            ) from $sl,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        String disease = "Trench fever";
        if($count.intValue() > 3) {
            diagnosis.setMostLikelyDisease(disease);
        }

        if ($count.intValue() > 2) {
            diagnosis.getHighChanceDiseases().add(disease);
        } else {
            diagnosis.getPossibleDiseases().add(disease);
        }
end