package sbz;

import sbz.biochemical.analysis.model.Results;
import sbz.biochemical.analysis.constants.ReferenceValues;
import sbz.biochemical.analysis.model.blood.analysis.Blood;
import sbz.biochemical.analysis.model.Gender;
import constants.ReferenceValues;
import constants.Diseases;

rule "Trombocytes level - High"
    when
        $r: Results(bloodAnalysis.blood.thrombocytes > ReferenceValues.THROMBOCYTES_MAX)
    then
        insert(new PossibleDisease(Diseases.STVARANJE_TROMBA));
end

rule "Trombocytes level - Low"
    when
        $r: Results(bloodAnalysis.blood.thrombocytes < ReferenceValues.THROMBOCYTES_MIN)
    then
        insert(new PossibleDisease(Diseases.RIZIK_OD_KRVARENJA));
end

rule "Erythrocytes level - Low"
    when
        $r: Results(bloodAnalysis.blood.erythrocytes < ReferenceValues.ERYTHROCYTES_MIN_MALE && gender == Gender.MALE)
    then
        insert(new PossibleDisease(Diseases.ANEMIJA));
end


