package sbz;

import sbz.biochemical.analysis.model.analysis.SymptomsAndDiseases;
import sbz.biochemical.analysis.model.analysis.Diagnosis;
import constants.SymptomsList;
import constants.Diseases;

global Diagnosis diagnosis;

rule "Aortic Aneurysm symptoms"
    when
        $s: SymptomsAndDiseases($sl: symptoms, $dl: diseasesList contains Diseases.AORTIC_ANEURYSM)
        $count: Number(intValue >= 2) from accumulate(
            String(
                toString() memberOf SymptomsList.aorticAneurysmSymptoms
            ) from $sl,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        String disease = "Aortic Aneurysm";
        if($count.intValue() > 3) {
            diagnosis.setMostLikelyDisease(disease);
        }

        if ($count.intValue() > 2) {
            diagnosis.getHighChanceDiseases().add(disease);
        } else {
            diagnosis.getPossibleDiseases().add(disease);
        }
end

rule "Keratitis symptoms"
    when
        $s: SymptomsAndDiseases($sl: symptoms, $dl: diseasesList contains Diseases.KERATITIS)
        $count: Number(intValue >= 2) from accumulate(
            String(
                toString() memberOf SymptomsList.keratitisSymptoms
            ) from $sl,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        String disease = "Keratitis";
        if($count.intValue() > 3) {
            diagnosis.setMostLikelyDisease(disease);
        }

        if ($count.intValue() > 2) {
            diagnosis.getHighChanceDiseases().add(disease);
        } else {
            diagnosis.getPossibleDiseases().add(disease);
        }
end

rule "Hansens disease symptoms"
    when
        $s: SymptomsAndDiseases($sl: symptoms, $dl: diseasesList contains Diseases.HANSENS_DISEASE)
        $count: Number(intValue >= 2) from accumulate(
            String(
                toString() memberOf SymptomsList.hansensDiseaseSymptoms
            ) from $sl,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        String disease = "Hansen's Disease";
        if($count.intValue() > 3) {
            diagnosis.setMostLikelyDisease(disease);
        }

        if ($count.intValue() > 2) {
            diagnosis.getHighChanceDiseases().add(disease);
        } else {
            diagnosis.getPossibleDiseases().add(disease);
        }
end